export const hotelData = [
  {
    name: 'Proper Hotel Downtown LA',
    stars: 4,
    price: {
      amount: 185,
      discountedAmount: 142,
      currency: '$',
      discountType: 'Special Discount',
      totalPrice: 710,
    },
    images: [
      '/images/los-angeles-hotel.png',
      '/images/los-angeles-hotel.png',
      '/images/los-angeles-hotel.png',
      '/images/los-angeles-hotel.png',
      '/images/los-angeles-hotel.png',
    ],
    rating: { value: 4.6, count: 5 },
    reviews: 312,
    location: 'Downtown Los Angeles',
    checkIn: '15:00',
    checkOut: '12:00',
    freeCancellation: true,
    roomType: ['King Room', 'Double Queen Room'],
  },
  {
    name: 'Hesperia Barcelona Del Mar',
    stars: 3,
    price: {
      amount: 72,
      discountedAmount: 48,
      currency: '$',
      discountType: 'Special Discount',
      totalPrice: 240,
    },
    images: [
      '/images/los-angeles-hotel.png',
      '/images/los-angeles-hotel.png',
      '/images/los-angeles-hotel.png',
      '/images/los-angeles-hotel.png',
      '/images/los-angeles-hotel.png',
    ],
    rating: { value: 3.9, count: 5 },
    reviews: 129,
    location: 'Near Poblenou Metro Station',
    checkIn: '14:00',
    checkOut: '12:00',
    freeCancellation: false,
    roomType: ['Double Room', 'Twin Room'],
  },
];
